import type { Metadata } from "next";
import {   Fredericka_the_Great, MuseoModerno, Rye, Stardos_Stencil  } from "next/font/google";
import "./globals.css";



const geistMono = Rye({
  subsets: ["latin"],
   weight: ["400"],
});

export const metadata: Metadata = {
  title: "Myora Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
         <link rel="icon" href="/favicon.ico" />
      </head> */}
      <body
        className={` ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
